AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to forward GitHub PR stats into Cloudwatch Metrics

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./main.zip
      Runtime: go1.x
      Environment:
        Variables:
          WEBHOOK_SECRET_TOKEN: examplesecret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /prstats
            Method: post

# TODO: define an appropriate policy/role for this
# TODO: define a Cloudwatch dashboard for this
# ---
# widgets:
# - type: metric
#   x: 0
#   y: 3
#   width: 3
#   height: 3
#   properties:
#     view: singleValue
#     stacked: false
#     metrics:
#     - - SSDL
#       - prdays
#       - repo
#       - kindlyops/prstats
#     region: us-west-2
#     title: Duration
#     period: 300
# - type: text
#   x: 0
#   y: 0
#   width: 6
#   height: 3
#   properties:
#     markdown: "\n# Software Development Lifecycle Stats\n\nWe try to keep pull requests
#       below 500 lines and open for less than a week. \n"
# - type: metric
#   x: 3
#   y: 3
#   width: 3
#   height: 3
#   properties:
#     view: singleValue
#     stacked: false
#     metrics:
#     - - SSDL
#       - prcount
#       - repo
#       - kindlyops/prstats
#     region: us-west-2
# - type: metric
#   x: 0
#   y: 6
#   width: 6
#   height: 6
#   properties:
#     view: timeSeries
#     stacked: false
#     metrics:
#     - - SSDL
#       - prsize
#       - repo
#       - kindlyops/prstats
#     region: us-west-2
