AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to forward GitHub PR stats into Cloudwatch Metrics 

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./main.zip
      Runtime: go1.x
      Environment:
        Variables:
          WEBHOOK_SECRET_TOKEN: examplesecret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /prstats
            Method: post

# TODO: define an appropriate policy/role for this
# TODO: define a Cloudwatch dashboard for this
