AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to forward GitHub PR stats into Cloudwatch Metrics

Parameters: 
  RepoName: 
    Type: "String"
    Description: "The name of the GitHub repo you want stats for, in the form 'owner/repo'"

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./main.zip
      Runtime: go1.x
      Environment:
        Variables:
          WEBHOOK_SECRET_TOKEN: examplesecret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /prstats
            Method: post
      Role: !Sub ${PublishMetricsRole.Arn}

  PublishMetricsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PublishMetricsRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole

  PublishMetricsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PublishMetricsPolicy
      Roles:
      - !Ref PublishMetricsRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - cloudwatch:PutDashboard
          - cloudwatch:PutMetricData
          Resource: "*"


  MetricsDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: GitHubPullRequestStats
      DashboardBody: !Sub |
        {
            "widgets": [
                {
                    "type": "text",
                    "x": 0,
                    "y": 0,
                    "width": 6,
                    "height": 3,
                    "properties": {
                        "markdown": "\n# Software Development Lifecycle Stats\n\nWe try to keep pull requests below 500 lines and open for less than a week. \n"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 3,
                    "width": 3,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "stacked": false,
                        "metrics": [
                            [ "SSDL", "prdays", "repo", "${RepoName}" ]
                        ],
                        "region": "${AWS::Region}",
                        "title": "Duration",
                        "period": 300
                    }
                },
                {
                    "type": "metric",
                    "x": 3,
                    "y": 3,
                    "width": 3,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "stacked": false,
                        "metrics": [
                            [ "SSDL", "prcount", "repo", "${RepoName}" ]
                        ],
                        "region": "${AWS::Region}"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 6,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "SSDL", "prsize", "repo", "${RepoName}" ]
                        ],
                        "region": "${AWS::Region}"
                    }
                }
            ]
        }
