version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kindlyops/prstats
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl -sS --location -o dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
      - run: chmod +x ./dep && ./dep ensure -vendor-only
      - run: go test
